### PR TITLE
Log error

### PR DESCRIPTION
**Pull request by KarinaMendez2**

### CODE REVIEW

**Comment by wilkus27** [comment]
@KarinaMendez2 I tested Sifter on this branch. I'm getting such error:

image

And these are logs in console:

image

**Comment by wilkus27** [comment]
I tried to install python 2 for this project using pyenv. Then run command from the read me: `python -m SimpleHTTPServer 8080`. But I'm getting the same error for the same book (Life, Liberty and a Pursuit of Happines). These are my logs from terminal.

image

I tried this on branch from this PR and the main one (gh-pages).

**Comment by ajluk** [comment]
Hi @KarinaMendez2 @philschatz! I have tested sifter locally on my machine and I've got such log error:
image
I have checkout `log_error` branch but the error still persists: 
image
I needed also to switch to older python version (from 3 to 2).

**UPDATE**
I have run the localhost server today again and the above errors are gone for some reason :thinking: but the searching process has stop on the same book as on Natalia's machine: 
image
Here is the  log output: 
image

**Comment by wilkus27** [comment]
### UPDATE
@jarosik10 has the same problem for the same book. He tried to remove locally

```
{
        "collection_id": "col31596",
        "server": "cnx.org",
        "style": "ap-history",
        "tutor_only": true,
        "books": [
          {
            "uuid": "36004586-651c-4ded-af87-203aca22d946",
            "slug": "life-liberty-and-pursuit-happiness"
          }
        ]
      },
```
from `approved-book-list.json` and it works for other books after that one.

**Pull request merged**
